In [5]:
import numpy as np

In [6]:
# sigmoid function
def nonlin(x, deriv=False):
  if deriv == True:
    return x * (1-x)
  return 1 / (1+np.exp(-x))


In [65]:
# input dataset
X = np.array([
  [0, 0, 1],
  [0, 1, 1],
  [1, 0, 1],
  [1, 1, 1],
])
print(X)

# output dataset
y = np.array([[0, 0, 1, 1]]).T
print(y)

[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]
[[0]
 [0]
 [1]
 [1]]


In [73]:
def learning(iter_cnt: int = 10_000):
  # seed random numbers to make calculation deterministic (it seems good practice)
  np.random.seed(1)

  # initialize weights randomly with mean 0
  syn0 = 2 * np.random.random((3, 1)) - 1

  # learning
  for _ in range(iter_cnt):
    # forward propagation
    layer0 = X
    layer1 = nonlin(np.dot(layer0, syn0))

    # calc error
    layer1_error = y - layer1

    # multiply how much we missed by the slope of the sigmoid at the values in layer1
    layer1_delta = layer1_error * nonlin(layer1, True)

    # update weights
    syn0 += np.dot(layer0.T, layer1_delta)

  print("Training result:")
  print(layer1)

  print("Values that we trying to predict:")
  print(y)

In [82]:
learning()

Training result:
[[0.00966449]
 [0.00786506]
 [0.99358898]
 [0.99211957]]
Values that we trying to predict:
[[0]
 [0]
 [1]
 [1]]
